# syntax = docker/dockerfile:1

FROM node:22-slim AS base

ARG PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable
RUN yarn set version stable

WORKDIR /app

FROM base AS dependencies

COPY package.json yarn.lock .yarnrc.yml ./
# RUN npm ci
RUN yarn --immutable
# TODO move this to a separate testing layer?
RUN sudo yarn playwright install-deps    


FROM base AS build

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN yarn build

FROM base AS run

ENV NODE_ENV=production
ENV PORT=$PORT

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=build /app/public ./public
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE $PORT

ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]

FROM base as dev
ENV NODE_ENV=development
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
# COPY the playwright install to the dev container?
# RUN yarn playwright install
# COPY --from=dependencies /app/.cache ./.cache
COPY . .