services:

  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d visadb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_DB: visadb
      POSTGRES_PASSWORD: pgpass
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    build:
      context: ./backend
      args:  # match VS Code User / Group ID so generated files share permissions
        UID: 1000
        GID: 1000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/code
    environment:
      DB_CONNECTION_STRING: "postgresql://pguser:pgpass@db:5432/visadb"
    command: >
      sh -c "alembic upgrade head && fastapi run app/main.py --host 0.0.0.0 --port 8000 --reload"
  
  frontend:
    build:
      dockerfile: prod.Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
 
volumes:
  postgres-data:
